version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=query-ms-db
      - POSTGRES_USER=query-ms
      - POSTGRES_PASSWORD=secret

    ports:
      - "5434:5432"
